-- Copy and paste this script into your Supabase SQL Editor

-- 1. Create Tables (Order is important for Foreign Keys)

CREATE TABLE IF NOT EXISTS public.dprd_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  party TEXT DEFAULT 'PAN',
  phone TEXT,
  photo_url TEXT,
  is_active SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('admin', 'superadmin', 'aspirator')),
  dprd_member_id BIGINT REFERENCES public.dprd_members(id),
  failed_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.aspirasi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_no TEXT NOT NULL UNIQUE,
  dprd_member_id BIGINT NOT NULL REFERENCES public.dprd_members(id),
  type TEXT NOT NULL CHECK(type IN ('penetapan', 'perubahan')),
  proposer_name TEXT NOT NULL,
  proposer_phone TEXT,
  proposer_address TEXT,
  description TEXT,
  budget_amount NUMERIC NOT NULL DEFAULT 0,
  fiscal_year INTEGER NOT NULL,
  status TEXT DEFAULT 'draft' CHECK(status IN ('draft', 'verified', 'rejected')),
  created_by BIGINT NOT NULL REFERENCES public.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aspirasi_id BIGINT NOT NULL REFERENCES public.aspirasi(id) ON DELETE CASCADE,
  file_path TEXT NOT NULL,
  original_name TEXT,
  file_size INTEGER,
  uploaded_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create Indexes
CREATE INDEX IF NOT EXISTS idx_aspirasi_dprd ON public.aspirasi(dprd_member_id);
CREATE INDEX IF NOT EXISTS idx_aspirasi_year ON public.aspirasi(fiscal_year);
CREATE INDEX IF NOT EXISTS idx_aspirasi_type ON public.aspirasi(type);
CREATE INDEX IF NOT EXISTS idx_aspirasi_ref ON public.aspirasi(reference_no);
CREATE INDEX IF NOT EXISTS idx_photos_aspirasi ON public.photos(aspirasi_id);

-- 3. Insert Initial Data (Superadmin & DPRD Members from seed)
-- Using ON CONFLICT DO UPDATE to forcefully overwrite any old dummy data
INSERT INTO public.dprd_members (id, name, party, phone) VALUES 
  (1, 'Basuki, S.E', 'PAN', '-'),
  (2, 'Widodo, S.H', 'PAN', '-'),
  (3, 'Purwanto, S.H', 'PAN', '-'),
  (4, 'Alex Fitroh Hadi Pornomo', 'PAN', '-')
ON CONFLICT (id) DO UPDATE SET 
  name = EXCLUDED.name,
  party = EXCLUDED.party,
  phone = EXCLUDED.phone;

-- NOTE: password is 'pan123' for all early accounts
INSERT INTO public.users (id, username, full_name, role, password_hash, dprd_member_id)
VALUES 
  (1, 'pan.admin', 'Super Administrator', 'superadmin', '$2a$10$wJt0FwB1V6gNzvP2T5K3xOnrR.q.yZ4oPxg1H2yI9A1K4qZ.M0O5W', NULL),
  (2, 'basuki.admin', 'Admin Basuki', 'admin', '$2a$10$wJt0FwB1V6gNzvP2T5K3xOnrR.q.yZ4oPxg1H2yI9A1K4qZ.M0O5W', 1),
  (3, 'widodo.admin', 'Admin Widodo', 'admin', '$2a$10$wJt0FwB1V6gNzvP2T5K3xOnrR.q.yZ4oPxg1H2yI9A1K4qZ.M0O5W', 2),
  (4, 'purwanto.admin', 'Admin Purwanto', 'admin', '$2a$10$wJt0FwB1V6gNzvP2T5K3xOnrR.q.yZ4oPxg1H2yI9A1K4qZ.M0O5W', 3),
  (5, 'alex.admin', 'Admin Alex Fitroh', 'admin', '$2a$10$wJt0FwB1V6gNzvP2T5K3xOnrR.q.yZ4oPxg1H2yI9A1K4qZ.M0O5W', 4)
ON CONFLICT (id) DO UPDATE SET
  username = EXCLUDED.username,
  full_name = EXCLUDED.full_name,
  role = EXCLUDED.role,
  password_hash = EXCLUDED.password_hash,
  dprd_member_id = EXCLUDED.dprd_member_id;

-- Resync the ID sequences to prevent insertion conflicts
SELECT setval('public.dprd_members_id_seq', (SELECT MAX(id) FROM public.dprd_members));
SELECT setval('public.users_id_seq', (SELECT MAX(id) FROM public.users));

-- 4. Setup Storage
-- Note: Go to Supabase Dashboard -> Storage -> Create a new bucket named 'uploads' manually
-- And make sure to set the bucket to "Public" so images can be viewed.
-- Storage creation programmatic query is removed because it requires higher privileges in Supabase.
