-- Copy and paste this script into your Supabase SQL Editor

-- 1. Create Tables (Order is important for Foreign Keys)

CREATE TABLE IF NOT EXISTS public.dprd_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  party TEXT DEFAULT 'PAN',
  phone TEXT,
  photo_url TEXT,
  is_active SMALLINT DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('admin', 'superadmin', 'aspirator')),
  dprd_member_id BIGINT REFERENCES public.dprd_members(id),
  failed_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.aspirasi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference_no TEXT NOT NULL UNIQUE,
  dprd_member_id BIGINT NOT NULL REFERENCES public.dprd_members(id),
  type TEXT NOT NULL CHECK(type IN ('penetapan', 'perubahan')),
  proposer_name TEXT NOT NULL,
  proposer_phone TEXT,
  proposer_address TEXT,
  description TEXT,
  budget_amount NUMERIC NOT NULL DEFAULT 0,
  fiscal_year INTEGER NOT NULL,
  status TEXT DEFAULT 'draft' CHECK(status IN ('draft', 'verified', 'rejected')),
  created_by BIGINT NOT NULL REFERENCES public.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  aspirasi_id BIGINT NOT NULL REFERENCES public.aspirasi(id) ON DELETE CASCADE,
  file_path TEXT NOT NULL,
  original_name TEXT,
  file_size INTEGER,
  uploaded_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create Indexes
CREATE INDEX IF NOT EXISTS idx_aspirasi_dprd ON public.aspirasi(dprd_member_id);
CREATE INDEX IF NOT EXISTS idx_aspirasi_year ON public.aspirasi(fiscal_year);
CREATE INDEX IF NOT EXISTS idx_aspirasi_type ON public.aspirasi(type);
CREATE INDEX IF NOT EXISTS idx_aspirasi_ref ON public.aspirasi(reference_no);
CREATE INDEX IF NOT EXISTS idx_photos_aspirasi ON public.photos(aspirasi_id);

-- 3. Insert Initial Data (Superadmin & DPRD Members from seed)
-- Using ON CONFLICT to avoid errors if run multiple times
INSERT INTO public.dprd_members (id, name, party, phone) VALUES 
  (1, 'Agus Sudarto', 'PAN', '081234567890'),
  (2, 'Budi Santoso', 'PAN', '081234567891'),
  (3, 'Citra Kirana', 'PAN', '081234567892'),
  (4, 'Deni Sumargo', 'PAN', '081234567893'),
  (5, 'Eka Prasetya', 'PAN', '081234567894')
ON CONFLICT (id) DO NOTHING;

-- NOTE: password is 'pan123'
INSERT INTO public.users (id, username, full_name, role, password_hash)
VALUES (1, 'pan.admin', 'Super Administrator', 'superadmin', '$2a$10$wJt0FwB1V6gNzvP2T5K3xOnrR.q.yZ4oPxg1H2yI9A1K4qZ.M0O5W')
ON CONFLICT (id) DO NOTHING;

-- Resync the ID sequences to prevent insertion conflicts
SELECT setval('public.dprd_members_id_seq', (SELECT MAX(id) FROM public.dprd_members));
SELECT setval('public.users_id_seq', (SELECT MAX(id) FROM public.users));

-- 4. Setup Storage
-- Note: Go to Supabase Dashboard -> Storage -> Create a new bucket named 'uploads' manually
-- And make sure to set the bucket to "Public" so images can be viewed.
-- Storage creation programmatic query is removed because it requires higher privileges in Supabase.
